# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list

  install-bin:
    desc: "Установак зависимых пакетов"
    aliases:
      - deps
    vars:
      PATH: "{{.TASKFILE_DIR}}/bin"
    cmds:
      - echo "Install deps to {{.PATH}}"
      - GOBIN={{.PATH}} go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - GOBIN={{.PATH}} go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - GOBIN={{.PATH}} go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
      - GOBIN={{.PATH}} go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
      - GOBIN={{.PATH}} go install github.com/bufbuild/buf/cmd/buf@latest
      - GOBIN={{.PATH}} go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.0.2
      - GOBIN={{.PATH}} go install github.com/vektra/mockery/v3@v3.5.3
  lint:
    desc: "Запуск линтера"
    vars:
      PATH: "{{.TASKFILE_DIR}}/bin"
    cmds:
      - ./bin/golangci-lint run ./...


  proto-generate:
    desc: "Регенерация файлов proto-файлов"
    aliases:
      - pbg
    cmds:
      - cmd: ./bin/buf generate

  generate:
    desc: "полная ре-/генерация"
    aliases:
      - gen
    cmds:
      - task: pbg

  mockery:
    desc: "генерация моков"
    cmds:
      - ./bin/mockery
