// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/jenny/types/entity.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Entity (Сущность)
type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Attributes    []*Entity_Attribute    `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_api_jenny_types_entity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_api_jenny_types_entity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_api_jenny_types_entity_proto_rawDescGZIP(), []int{0}
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Entity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Entity) GetAttributes() []*Entity_Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// Attribute (Атрибут)
type Entity_Attribute struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // Униальный идентификатор атрибута
	Label         string                    `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`             // Наименование атрибута
	Description   string                    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // Описание атрибута
	Values        []*Entity_Attribute_Value `protobuf:"bytes,4,rep,name=values,proto3" json:"values,omitempty"`           // значения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity_Attribute) Reset() {
	*x = Entity_Attribute{}
	mi := &file_api_jenny_types_entity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity_Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity_Attribute) ProtoMessage() {}

func (x *Entity_Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_api_jenny_types_entity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity_Attribute.ProtoReflect.Descriptor instead.
func (*Entity_Attribute) Descriptor() ([]byte, []int) {
	return file_api_jenny_types_entity_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Entity_Attribute) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity_Attribute) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Entity_Attribute) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Entity_Attribute) GetValues() []*Entity_Attribute_Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// Value (Значение)
type Entity_Attribute_Value struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Id          string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // Уникальный идентификатор значения
	Label       string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`             // заголовок значения
	Description string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // описание значения
	// Types that are valid to be assigned to Value:
	//
	//	*Entity_Attribute_Value_StringValue
	//	*Entity_Attribute_Value_IntValue
	//	*Entity_Attribute_Value_FloatValue
	//	*Entity_Attribute_Value_BoolValue
	//	*Entity_Attribute_Value_DatetimeValue
	//	*Entity_Attribute_Value_BinaryValue
	Value         isEntity_Attribute_Value_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity_Attribute_Value) Reset() {
	*x = Entity_Attribute_Value{}
	mi := &file_api_jenny_types_entity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity_Attribute_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity_Attribute_Value) ProtoMessage() {}

func (x *Entity_Attribute_Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_jenny_types_entity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity_Attribute_Value.ProtoReflect.Descriptor instead.
func (*Entity_Attribute_Value) Descriptor() ([]byte, []int) {
	return file_api_jenny_types_entity_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Entity_Attribute_Value) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity_Attribute_Value) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Entity_Attribute_Value) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Entity_Attribute_Value) GetValue() isEntity_Attribute_Value_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Entity_Attribute_Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Entity_Attribute_Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Entity_Attribute_Value) GetIntValue() int32 {
	if x != nil {
		if x, ok := x.Value.(*Entity_Attribute_Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Entity_Attribute_Value) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*Entity_Attribute_Value_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *Entity_Attribute_Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Entity_Attribute_Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Entity_Attribute_Value) GetDatetimeValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Entity_Attribute_Value_DatetimeValue); ok {
			return x.DatetimeValue
		}
	}
	return 0
}

func (x *Entity_Attribute_Value) GetBinaryValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*Entity_Attribute_Value_BinaryValue); ok {
			return x.BinaryValue
		}
	}
	return nil
}

type isEntity_Attribute_Value_Value interface {
	isEntity_Attribute_Value_Value()
}

type Entity_Attribute_Value_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"` // Строковое значение
}

type Entity_Attribute_Value_IntValue struct {
	IntValue int32 `protobuf:"varint,5,opt,name=int_value,json=intValue,proto3,oneof"` // Целочисленное значение
}

type Entity_Attribute_Value_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,6,opt,name=float_value,json=floatValue,proto3,oneof"` // Значение с плавающей точкой
}

type Entity_Attribute_Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,7,opt,name=bool_value,json=boolValue,proto3,oneof"` // Булево значение
}

type Entity_Attribute_Value_DatetimeValue struct {
	DatetimeValue int64 `protobuf:"varint,8,opt,name=datetime_value,json=datetimeValue,proto3,oneof"` // Дата/время (timestamp)
}

type Entity_Attribute_Value_BinaryValue struct {
	BinaryValue []byte `protobuf:"bytes,9,opt,name=binary_value,json=binaryValue,proto3,oneof"` // Бинарные данные
}

func (*Entity_Attribute_Value_StringValue) isEntity_Attribute_Value_Value() {}

func (*Entity_Attribute_Value_IntValue) isEntity_Attribute_Value_Value() {}

func (*Entity_Attribute_Value_FloatValue) isEntity_Attribute_Value_Value() {}

func (*Entity_Attribute_Value_BoolValue) isEntity_Attribute_Value_Value() {}

func (*Entity_Attribute_Value_DatetimeValue) isEntity_Attribute_Value_Value() {}

func (*Entity_Attribute_Value_BinaryValue) isEntity_Attribute_Value_Value() {}

var File_api_jenny_types_entity_proto protoreflect.FileDescriptor

const file_api_jenny_types_entity_proto_rawDesc = "" +
	"\n" +
	"\x1capi/jenny/types/entity.proto\x12\x05types\"\xc7\x04\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x127\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2\x17.types.Entity.AttributeR\n" +
	"attributes\x1a\xbb\x03\n" +
	"\tAttribute\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\x06values\x18\x04 \x03(\v2\x1d.types.Entity.Attribute.ValueR\x06values\x1a\xae\x02\n" +
	"\x05Value\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12#\n" +
	"\fstring_value\x18\x04 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x05 \x01(\x05H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x06 \x01(\x02H\x00R\n" +
	"floatValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\a \x01(\bH\x00R\tboolValue\x12'\n" +
	"\x0edatetime_value\x18\b \x01(\x03H\x00R\rdatetimeValue\x12#\n" +
	"\fbinary_value\x18\t \x01(\fH\x00R\vbinaryValueB\a\n" +
	"\x05valueB*Z(github.com/Z00mZE/jenny/pb/service/typesb\x06proto3"

var (
	file_api_jenny_types_entity_proto_rawDescOnce sync.Once
	file_api_jenny_types_entity_proto_rawDescData []byte
)

func file_api_jenny_types_entity_proto_rawDescGZIP() []byte {
	file_api_jenny_types_entity_proto_rawDescOnce.Do(func() {
		file_api_jenny_types_entity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_jenny_types_entity_proto_rawDesc), len(file_api_jenny_types_entity_proto_rawDesc)))
	})
	return file_api_jenny_types_entity_proto_rawDescData
}

var file_api_jenny_types_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_jenny_types_entity_proto_goTypes = []any{
	(*Entity)(nil),                 // 0: types.Entity
	(*Entity_Attribute)(nil),       // 1: types.Entity.Attribute
	(*Entity_Attribute_Value)(nil), // 2: types.Entity.Attribute.Value
}
var file_api_jenny_types_entity_proto_depIdxs = []int32{
	1, // 0: types.Entity.attributes:type_name -> types.Entity.Attribute
	2, // 1: types.Entity.Attribute.values:type_name -> types.Entity.Attribute.Value
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_jenny_types_entity_proto_init() }
func file_api_jenny_types_entity_proto_init() {
	if File_api_jenny_types_entity_proto != nil {
		return
	}
	file_api_jenny_types_entity_proto_msgTypes[2].OneofWrappers = []any{
		(*Entity_Attribute_Value_StringValue)(nil),
		(*Entity_Attribute_Value_IntValue)(nil),
		(*Entity_Attribute_Value_FloatValue)(nil),
		(*Entity_Attribute_Value_BoolValue)(nil),
		(*Entity_Attribute_Value_DatetimeValue)(nil),
		(*Entity_Attribute_Value_BinaryValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_jenny_types_entity_proto_rawDesc), len(file_api_jenny_types_entity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_jenny_types_entity_proto_goTypes,
		DependencyIndexes: file_api_jenny_types_entity_proto_depIdxs,
		MessageInfos:      file_api_jenny_types_entity_proto_msgTypes,
	}.Build()
	File_api_jenny_types_entity_proto = out.File
	file_api_jenny_types_entity_proto_goTypes = nil
	file_api_jenny_types_entity_proto_depIdxs = nil
}
