// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/jenny/types/event.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*Event_Insert_
	//	*Event_Update_
	//	*Event_Delete_
	Event         isEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_jenny_types_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_jenny_types_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_jenny_types_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetEvent() isEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Event) GetInsert() *Event_Insert {
	if x != nil {
		if x, ok := x.Event.(*Event_Insert_); ok {
			return x.Insert
		}
	}
	return nil
}

func (x *Event) GetUpdate() *Event_Update {
	if x != nil {
		if x, ok := x.Event.(*Event_Update_); ok {
			return x.Update
		}
	}
	return nil
}

func (x *Event) GetDelete() *Event_Delete {
	if x != nil {
		if x, ok := x.Event.(*Event_Delete_); ok {
			return x.Delete
		}
	}
	return nil
}

type isEvent_Event interface {
	isEvent_Event()
}

type Event_Insert_ struct {
	Insert *Event_Insert `protobuf:"bytes,1,opt,name=insert,proto3,oneof"`
}

type Event_Update_ struct {
	Update *Event_Update `protobuf:"bytes,2,opt,name=update,proto3,oneof"`
}

type Event_Delete_ struct {
	Delete *Event_Delete `protobuf:"bytes,3,opt,name=delete,proto3,oneof"`
}

func (*Event_Insert_) isEvent_Event() {}

func (*Event_Update_) isEvent_Event() {}

func (*Event_Delete_) isEvent_Event() {}

type Event_Insert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Entity                `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Insert) Reset() {
	*x = Event_Insert{}
	mi := &file_api_jenny_types_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Insert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Insert) ProtoMessage() {}

func (x *Event_Insert) ProtoReflect() protoreflect.Message {
	mi := &file_api_jenny_types_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Insert.ProtoReflect.Descriptor instead.
func (*Event_Insert) Descriptor() ([]byte, []int) {
	return file_api_jenny_types_event_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Event_Insert) GetData() *Entity {
	if x != nil {
		return x.Data
	}
	return nil
}

type Event_Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Update) Reset() {
	*x = Event_Update{}
	mi := &file_api_jenny_types_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Update) ProtoMessage() {}

func (x *Event_Update) ProtoReflect() protoreflect.Message {
	mi := &file_api_jenny_types_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Update.ProtoReflect.Descriptor instead.
func (*Event_Update) Descriptor() ([]byte, []int) {
	return file_api_jenny_types_event_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Event_Update) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Event_Delete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event_Delete) Reset() {
	*x = Event_Delete{}
	mi := &file_api_jenny_types_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event_Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event_Delete) ProtoMessage() {}

func (x *Event_Delete) ProtoReflect() protoreflect.Message {
	mi := &file_api_jenny_types_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event_Delete.ProtoReflect.Descriptor instead.
func (*Event_Delete) Descriptor() ([]byte, []int) {
	return file_api_jenny_types_event_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Event_Delete) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_jenny_types_event_proto protoreflect.FileDescriptor

const file_api_jenny_types_event_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/jenny/types/event.proto\x12\x05types\x1a\x1capi/jenny/types/entity.proto\"\xfe\x01\n" +
	"\x05Event\x12-\n" +
	"\x06insert\x18\x01 \x01(\v2\x13.types.Event.InsertH\x00R\x06insert\x12-\n" +
	"\x06update\x18\x02 \x01(\v2\x13.types.Event.UpdateH\x00R\x06update\x12-\n" +
	"\x06delete\x18\x03 \x01(\v2\x13.types.Event.DeleteH\x00R\x06delete\x1a+\n" +
	"\x06Insert\x12!\n" +
	"\x04data\x18\x01 \x01(\v2\r.types.EntityR\x04data\x1a\x18\n" +
	"\x06Update\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x1a\x18\n" +
	"\x06Delete\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02idB\a\n" +
	"\x05eventB*Z(github.com/Z00mZE/jenny/pb/service/typesb\x06proto3"

var (
	file_api_jenny_types_event_proto_rawDescOnce sync.Once
	file_api_jenny_types_event_proto_rawDescData []byte
)

func file_api_jenny_types_event_proto_rawDescGZIP() []byte {
	file_api_jenny_types_event_proto_rawDescOnce.Do(func() {
		file_api_jenny_types_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_jenny_types_event_proto_rawDesc), len(file_api_jenny_types_event_proto_rawDesc)))
	})
	return file_api_jenny_types_event_proto_rawDescData
}

var file_api_jenny_types_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_jenny_types_event_proto_goTypes = []any{
	(*Event)(nil),        // 0: types.Event
	(*Event_Insert)(nil), // 1: types.Event.Insert
	(*Event_Update)(nil), // 2: types.Event.Update
	(*Event_Delete)(nil), // 3: types.Event.Delete
	(*Entity)(nil),       // 4: types.Entity
}
var file_api_jenny_types_event_proto_depIdxs = []int32{
	1, // 0: types.Event.insert:type_name -> types.Event.Insert
	2, // 1: types.Event.update:type_name -> types.Event.Update
	3, // 2: types.Event.delete:type_name -> types.Event.Delete
	4, // 3: types.Event.Insert.data:type_name -> types.Entity
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_jenny_types_event_proto_init() }
func file_api_jenny_types_event_proto_init() {
	if File_api_jenny_types_event_proto != nil {
		return
	}
	file_api_jenny_types_entity_proto_init()
	file_api_jenny_types_event_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_Insert_)(nil),
		(*Event_Update_)(nil),
		(*Event_Delete_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_jenny_types_event_proto_rawDesc), len(file_api_jenny_types_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_jenny_types_event_proto_goTypes,
		DependencyIndexes: file_api_jenny_types_event_proto_depIdxs,
		MessageInfos:      file_api_jenny_types_event_proto_msgTypes,
	}.Build()
	File_api_jenny_types_event_proto = out.File
	file_api_jenny_types_event_proto_goTypes = nil
	file_api_jenny_types_event_proto_depIdxs = nil
}
